version: "3.9"

services:
    web:
        ports:
            - 5001:5001
        networks:
            - webnet
        environment:
            BASE_URL: "${BASE_URL}"
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - node_modules:/app/node_modules
            - ./:/app
        # depends_on:
        #     - api
    # api:
    #     ports:
    #         - 3000:3000
    #     hostname: backend
    #     networks:
    #         - webnet
    #     image: tolumide/sysare_api
networks:
    webnet:
volumes:
    node_modules: